version: '3'
services:
  app:
    container_name: linqbin
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      PUBLIC_API_URL: '${PUBLIC_API_URL}'
      PUBLIC_BLOCKED_USER_AGENTS: '${PUBLIC_BLOCKED_USER_AGENTS}'
    ports:
      - '${PORT}:${PORT}'
    command: 'node build'