version: '3'
services:
  app:
    container_name: linqbin
    image: linqbin/linqbin:latest
    env_file:
      - .env
    environment:
      PUBLIC_API_URL: '${PUBLIC_API_URL}'
      PUBLIC_BLOCKED_USER_AGENTS: '${PUBLIC_BLOCKED_USER_AGENTS}'
    ports:
      - '${PORT}:${PORT}'
    command: 'node build'